### ISSUE TITLE
Navbar on 4k

### ISSUE THREAD

**Issue by derpmarine168** [SurreyHeathYouthCouncil/SurreyHeathYouthCouncil.github.io#2]
the issue is pretty simple problem, pretty easy fix:
720p monitor:
![surreyheathyc github io_720](https://user-images.githubusercontent.com/28905212/38247425-25a7a476-373d-11e8-9879-77ddc7cb12a5.png)
1080p monitor:
![surreyheathyc github io_1080](https://user-images.githubusercontent.com/28905212/38247426-25c4a8a0-373d-11e8-8343-46b13204bc49.png)
4k monitor:
![surreyheathyc github io_4kuw](https://user-images.githubusercontent.com/28905212/38247427-25e1c67e-373d-11e8-8afd-68cac44104c7.png)
you can see how small the navbar gets.

**Comment by derpmarine168** [comment]
ok

**Comment by JW-20** [comment]
Couldn't fix it. Your turn to try.

**Comment by derpmarine168** [comment]
where is the style for the navbar?

**Comment by JW-20** [comment]
Mostly through w3.css. The image and links have a tiny bit of styling in
frontpage.css, right at the end

**Comment by derpmarine168** [comment]
i put it on your todo list ages ago for you to remove that. it's not even minified! and if it's in w3.css, there's not much i can do.

**Comment by derpmarine168** [comment]
w3.css is a whole library
